package com.example.pty.mapper;

import com.example.pty.mode.Publish;
import com.example.pty.mode.PublishExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PublishMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Oct 23 20:40:47 CST 2019
     */
    long countByExample(PublishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Oct 23 20:40:47 CST 2019
     */
    int deleteByExample(PublishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Oct 23 20:40:47 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Oct 23 20:40:47 CST 2019
     */
    int insert(Publish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Oct 23 20:40:47 CST 2019
     */
    int insertSelective(Publish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Oct 23 20:40:47 CST 2019
     */
    List<Publish> selectByExampleWithRowbounds(PublishExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Oct 23 20:40:47 CST 2019
     */
    List<Publish> selectByExample(PublishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Oct 23 20:40:47 CST 2019
     */
    Publish selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Oct 23 20:40:47 CST 2019
     */
    int updateByExampleSelective(@Param("record") Publish record, @Param("example") PublishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Oct 23 20:40:47 CST 2019
     */
    int updateByExample(@Param("record") Publish record, @Param("example") PublishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Oct 23 20:40:47 CST 2019
     */
    int updateByPrimaryKeySelective(Publish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish
     *
     * @mbg.generated Wed Oct 23 20:40:47 CST 2019
     */
    int updateByPrimaryKey(Publish record);
}